import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  large_title_regular: {
    fontSize: 34,
    fontWeight: '400',
    lineHeight: 41,
    letterSpacing: -0.4,
  },
  large_title_bold: {
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 41,
    letterSpacing: -0.4,
  },
  title_1_regular: {
    fontSize: 28,
    fontWeight: '400',
    lineHeight: 34,
    letterSpacing: -0.4,
  },
  title_1_bold: {
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 34,
    letterSpacing: -0.4,
  },
  title_2_regular: {
    fontSize: 22,
    fontWeight: '400',
    lineHeight: 28,
    letterSpacing: -0.4,
  },
  title_2_bold: {
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
    letterSpacing: -0.4,
  },
  title_3_regular: {
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 25,
    letterSpacing: -0.4,
  },
  title_3_bold: {
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 25,
    letterSpacing: -0.4,
  },
  headline_semibold: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  headline_semibold_italic: {
    fontSize: 17,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  body_regular: {
    fontSize: 17,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  body_semibold: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  body_regular_italic: {
    fontSize: 17,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  body_semibold_italic: {
    fontSize: 17,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  callout_regular: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 21,
    letterSpacing: -0.4,
  },
  callout_semibold: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 21,
    letterSpacing: -0.4,
  },
  callout_regular_italic: {
    fontSize: 16,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: 21,
    letterSpacing: -0.4,
  },
  callout_semibold_italic: {
    fontSize: 16,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 21,
    letterSpacing: -0.4,
  },
  sub_headline_regular: {
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.4,
  },
  sub_headline_semibold: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: -0.4,
  },
  sub_headline_regular_italic: {
    fontSize: 15,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.4,
  },
  sub_headline_semibold_italic: {
    fontSize: 15,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: -0.4,
  },
  footnote_regular: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: -0.4,
  },
  footnote_semibold: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    letterSpacing: -0.4,
  },
  footnote_regular_italic: {
    fontSize: 13,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: -0.4,
  },
  footnote_semibold_italic: {
    fontSize: 13,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 18,
    letterSpacing: -0.4,
  },
  caption_1_regular: {
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: -0.4,
  },
  caption_1_semibold: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: -0.4,
  },
  caption_1_regular_italic: {
    fontSize: 12,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: -0.4,
  },
  caption_1_semibold_italic: {
    fontSize: 12,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: -0.4,
  },
  caption_2_regular: {
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 13,
    letterSpacing: -0.4,
  },
  caption_2_semibold: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
    letterSpacing: -0.4,
  },
  caption_2_regular_italic: {
    fontSize: 11,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: 13,
    letterSpacing: -0.4,
  },
  caption_2_semibold_italic: {
    fontSize: 11,
    fontStyle: 'italic',
    fontWeight: '600',
    lineHeight: 13,
    letterSpacing: -0.4,
  },
});
